using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
//Name: Marwan Ali
//Date: Nov 2 - Nov 12 2020
//Program: frmTicTacToe
//Purpose: To create a form that pops up when you die in the program swftSalv. Also get high 90. Additionally to inpress mom and Mr. Moniaga
namespace SpaceShipInvaders
{
    public partial class frmTicTacToe : Form
    {
        public frmTicTacToe()
        {
            InitializeComponent();
            btnArr = new Button[] { btnX1, btnX2, btnX3, btnY1, btnY2, btnY3, btnZ1, btnZ2, btnZ3 };//placing all buttons in an array
            btnList = btnArr.OfType<Button>().ToList();//converting the array of buttons to a list so I can use the bult-in functions .Add and .Remove when running my code
        }
        // int tgn = swftSalv.level;
        bool round = true; // assigning boolean round to true. This boolean will be used to determine weather its the players or the programs turn to play
        int scoreX;//score will be used to determine the score of the user
        int scoreO;//score will be used to determine the score of the computer
        Random rnd = new Random();//Generates a random number using the Random class
        Button[] btnArr;//creating an array of buttons
        List<Button> btnList;//creating a list of buttons
        private void tmrfontColourChange_Tick(object sender, EventArgs e)//timer used to transition between the coulours of the fonts
        {
            //.ForeColor sets the foreground color of the control. I learnt this here (https://stackoverflow.com/questions/10441000/how-to-programmatically-set-the-forecolor-of-a-label-to-its-default)
            //.FromArgb produces an 8-bit colour value (Red, Green, and Blue). I lenr this here (https://docs.microsoft.com/en-us/dotnet/api/system.drawing.color.fromargb?view=net-5.0)
            //rnd.Next(0, 255) generates a random number from 0 to 255 using the object rdn from thw class Random
            //lblticTacToe is the label that I want to transition the fint between
            lblticTacToe.ForeColor = Color.FromArgb(rnd.Next(0, 255), rnd.Next(0, 255), rnd.Next(0, 255), rnd.Next(0, 255));//rnd.Next generates a random number inbetween(0, 255)
        }

        private void clickEvent(object sender, EventArgs e)//this event called clickevent happens whenever a buttons is clicked from the 9 buttons in the TicTacToe game
        {
            //Convert the sender object as a button
            Button btn = (Button)sender;//Essentially this detects the button clicked and then places it in the btn variable using the Button class . I learnt this here(https://stackoverflow.com/questions/33299682/get-the-text-value-of-the-button-that-was-clicked)

            //generates a random number between 0 and the amount of elements in the btnList List - 1. I subtracted 1 because the function .Count counts the number of items in the List starting from 1, and since there are 9 buttons, .Count will read 9 items. 
            //We dont want that as in coding, the first index is considered to be index 0, the 2nd item is index 1. If you keep going the item 9 is considered index 8. Without the -1, rndIndex will generate an index from 0 to 9, which is impossible since there are only 9 items not ten if you count from 0 to 9 there are 10 digits.
            int rndIndex = rnd.Next(0, btnList.Count - 1);

            //We always want the List to be greater than 0. If the list isnt then there will be no more buttons to press, meaning the 
            //game has ended in the result of a loss, victory, or draw
            if (btnList.Count > 0)
            {
                //This if statment essentially checks weather it is the users turn or not using the round boolean variable
                if (round == true)
                {
                    // I will take the btn varibale from line 41 and setting it here.
                    //the button that was pressed by the User will be marked as X
                    btn.Text = "X";
                    //Disable the clicked button so that it can not be pressed on again
                    btn.Enabled = false;
                    //removes the clicked button from the btnList List so that later on it can not be auto-generated by the program 
                    //You will see later on what I mean by that
                    btnList.Remove(btn);
                    //After the user makes his turn, its the computers turn now, so we will change the round boolean to false to prep for the next step
                    round = false;
                    //This checks if the user made the winning move
                    winCheckX();//this is a method that I created to run code when the user wins
                    //this checks if the game ended in a draw
                    drawCheck();//this is a method that I created to run code when the game ended in a draw
                }
                //This code runs when it is no longer the users turn and it is the computers turn
                if (round == false)//this checks if its the computers turn 
                {
                    //This is where the program secures the win when it sees 2 Os in a row and its their turn
                    //Checking for oppurtunities in rows
                    if ((btnX1.Text != "O") && (btnX2.Text == "O") && (btnX3.Text == "O") && (btnX1.Text != "X"))
                    {
                        btnX1.Text = "O";//setting the button to the text "O"
                        btnX1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "O") && (btnX2.Text != "O") && (btnX3.Text == "O") && (btnX2.Text != "X"))
                    {
                        btnX2.Text = "O";//setting the button to the text "O"
                        btnX2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "O") && (btnX2.Text == "O") && (btnX3.Text != "O") && (btnX3.Text != "X"))
                    {
                        btnX3.Text = "O";//setting the button to the text "O"
                        btnX3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnY1.Text != "O") && (btnY2.Text == "O") && (btnY3.Text == "O") && (btnY1.Text != "X"))
                    {
                        btnY1.Text = "O";//setting the button to the text "O"
                        btnY1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnY1.Text == "O") && (btnY2.Text != "O") && (btnY3.Text == "O") && (btnY2.Text != "X"))
                    {
                        btnY2.Text = "O";//setting the button to the text "O"
                        btnY2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnY1.Text == "O") && (btnY2.Text == "O") && (btnY3.Text != "O") && (btnY3.Text != "X"))
                    {
                        btnY3.Text = "O";//setting the button to the text "O"
                        btnY3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnZ1.Text != "O") && (btnZ2.Text == "O") && (btnZ3.Text == "O") && (btnZ1.Text != "X"))
                    {
                        btnZ1.Text = "O";//setting the button to the text "O"
                        btnZ1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnZ1.Text == "O") && (btnZ2.Text != "O") && (btnZ3.Text == "O") && (btnZ2.Text != "X"))
                    {
                        btnZ2.Text = "O";//setting the button to the text "O"
                        btnZ2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnZ1.Text == "O") && (btnZ2.Text == "O") && (btnZ3.Text != "O") && (btnZ3.Text != "X"))
                    {
                        btnZ3.Text = "O";//setting the button to the text "O"
                        btnZ3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    //Checking for opportunities in columns
                    else if ((btnX1.Text != "O") && (btnY1.Text == "O") && (btnZ1.Text == "O") && (btnX1.Text != "X"))
                    {
                        btnX1.Text = "O";//setting the button to the text "O"
                        btnX1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "O") && (btnY1.Text != "O") && (btnZ1.Text == "O") && (btnY1.Text != "X"))
                    {
                        btnY1.Text = "O";//setting the button to the text "O"
                        btnY1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "O") && (btnY1.Text == "O") && (btnZ1.Text != "O") && (btnZ1.Text != "X"))
                    {
                        btnZ1.Text = "O";//setting the button to the text "O"
                        btnZ1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX2.Text != "O") && (btnY2.Text == "O") && (btnZ2.Text == "O") && (btnX2.Text != "X"))
                    {
                        btnX2.Text = "O";//setting the button to the text "O"
                        btnX2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX2.Text == "O") && (btnY2.Text != "O") && (btnZ2.Text == "O") && (btnY2.Text != "X"))
                    {
                        btnY2.Text = "O";//setting the button to the text "O"
                        btnY2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX2.Text == "O") && (btnY2.Text == "O") && (btnZ2.Text != "O") && (btnZ2.Text != "X"))
                    {
                        btnZ2.Text = "O";//setting the button to the text "O"
                        btnZ2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text != "O") && (btnY3.Text == "O") && (btnZ3.Text == "O") && (btnX3.Text != "X"))
                    {
                        btnX3.Text = "O";//setting the button to the text "O"
                        btnX3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text == "O") && (btnY3.Text != "O") && (btnZ3.Text == "O") && (btnY3.Text != "X"))
                    {
                        btnY3.Text = "O";//setting the button to the text "O"
                        btnY3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text == "O") && (btnY3.Text == "O") && (btnZ3.Text != "O") && (btnZ3.Text != "X"))
                    {
                        btnZ3.Text = "O";//setting the button to the text "O"
                        btnZ3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    //Checking for oppurtunities in diagonals
                    else if ((btnX1.Text != "O") && (btnY2.Text == "O") && (btnZ3.Text == "O") && (btnX1.Text != "X"))
                    {
                        btnX1.Text = "O";//setting the button to the text "O"
                        btnX1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "O") && (btnY2.Text != "O") && (btnZ3.Text == "O") && (btnY2.Text != "X"))
                    {
                        btnY2.Text = "O";//setting the button to the text "O"
                        btnY2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "O") && (btnY2.Text == "O") && (btnZ3.Text != "O") && (btnZ3.Text != "X"))
                    {
                        btnZ3.Text = "O";//setting the button to the text "O"
                        btnZ3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text != "O") && (btnY2.Text == "O") && (btnZ1.Text == "O") && (btnX3.Text != "X"))
                    {
                        btnX3.Text = "O";//setting the button to the text "O"
                        btnX3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text == "O") && (btnY2.Text != "O") && (btnZ1.Text == "O") && (btnY2.Text != "X"))
                    {
                        btnY2.Text = "O";//setting the button to the text "O"
                        btnY2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text == "O") && (btnY2.Text == "O") && (btnZ1.Text != "O") && (btnZ1.Text != "X"))
                    {
                        btnZ1.Text = "O";//setting the button to the text "O"
                        btnZ1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text != "X") && (btnX2.Text == "X") && (btnX3.Text == "X") && (btnX1.Text != "O"))
                    {
                        btnX1.Text = "O";//setting the button to the text "O"
                        btnX1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "X") && (btnX2.Text != "X") && (btnX3.Text == "X") && (btnX2.Text != "O"))
                    {
                        btnX2.Text = "O";//setting the button to the text "O"
                        btnX2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "X") && (btnX2.Text == "X") && (btnX3.Text != "X") && (btnX3.Text != "O"))
                    {
                        btnX3.Text = "O";//setting the button to the text "O"
                        btnX3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnY1.Text != "X") && (btnY2.Text == "X") && (btnY3.Text == "X") && (btnY1.Text != "O"))
                    {
                        btnY1.Text = "O";//setting the button to the text "O"
                        btnY1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnY1.Text == "X") && (btnY2.Text != "X") && (btnY3.Text == "X") && (btnY2.Text != "O"))
                    {
                        btnY2.Text = "O";//setting the button to the text "O"
                        btnY2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnY1.Text == "X") && (btnY2.Text == "X") && (btnY3.Text != "X") && (btnY3.Text != "O"))
                    {
                        btnY3.Text = "O";//setting the button to the text "O"
                        btnY3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnZ1.Text != "X") && (btnZ2.Text == "X") && (btnZ3.Text == "X") && (btnZ1.Text != "O"))
                    {
                        btnZ1.Text = "O";//setting the button to the text "O"
                        btnZ1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnZ1.Text == "X") && (btnZ2.Text != "X") && (btnZ3.Text == "X") && (btnZ2.Text != "O"))
                    {
                        btnZ2.Text = "O";//setting the button to the text "O"
                        btnZ2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnZ1.Text == "X") && (btnZ2.Text == "X") && (btnZ3.Text != "X") && (btnZ3.Text != "O"))
                    {
                        btnZ3.Text = "O";//setting the button to the text "O"
                        btnZ3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    //checking to block x rows
                    else if ((btnX1.Text != "X") && (btnY1.Text == "X") && (btnZ1.Text == "X") && (btnX1.Text != "O"))
                    {
                        btnX1.Text = "O";//setting the button to the text "O"
                        btnX1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "X") && (btnY1.Text != "X") && (btnZ1.Text == "X") && (btnY1.Text != "O"))
                    {
                        btnY1.Text = "O";//setting the button to the text "O"
                        btnY1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "X") && (btnY1.Text == "X") && (btnZ1.Text != "X") && (btnZ1.Text != "O"))
                    {
                        btnZ1.Text = "O";//setting the button to the text "O"
                        btnZ1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX2.Text != "X") && (btnY2.Text == "X") && (btnZ2.Text == "X") && (btnX2.Text != "O"))
                    {
                        btnX2.Text = "O";//setting the button to the text "O"
                        btnX2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX2.Text == "X") && (btnY2.Text != "X") && (btnZ2.Text == "X") && (btnY2.Text != "O"))
                    {
                        btnY2.Text = "O";//setting the button to the text "O"
                        btnY2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX2.Text == "X") && (btnY2.Text == "X") && (btnZ2.Text != "X") && (btnZ2.Text != "O"))
                    {
                        btnZ2.Text = "O";//setting the button to the text "O"
                        btnZ2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text != "X") && (btnY3.Text == "X") && (btnZ3.Text == "X") && (btnX3.Text != "O"))
                    {
                        btnX3.Text = "O";//setting the button to the text "O"
                        btnX3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text == "X") && (btnY3.Text != "X") && (btnZ3.Text == "X") && (btnY3.Text != "O"))
                    {
                        btnY3.Text = "O";//setting the button to the text "O"
                        btnY3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text == "X") && (btnY3.Text == "X") && (btnZ3.Text != "X") && (btnZ3.Text != "O"))
                    {
                        btnZ3.Text = "O";//setting the button to the text "O"
                        btnZ3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    //checking to block off x diagonals
                    else if ((btnX1.Text != "X") && (btnY2.Text == "X") && (btnZ3.Text == "X") && (btnX1.Text != "O"))
                    {
                        btnX1.Text = "O";//setting the button to the text "O"
                        btnX1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "X") && (btnY2.Text != "X") && (btnZ3.Text == "X") && (btnY2.Text != "O"))
                    {
                        btnY2.Text = "O";//setting the button to the text "O"
                        btnY2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX1.Text == "X") && (btnY2.Text == "X") && (btnZ3.Text != "X") && (btnZ3.Text != "O"))
                    {
                        btnZ3.Text = "O";//setting the button to the text "O"
                        btnZ3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text != "X") && (btnY2.Text == "X") && (btnZ1.Text == "X") && (btnX3.Text != "O"))
                    {
                        btnX3.Text = "O";//setting the button to the text "O"
                        btnX3.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text == "X") && (btnY2.Text != "X") && (btnZ1.Text == "X") && (btnY2.Text != "O"))
                    {
                        btnY2.Text = "O";//setting the button to the text "O"
                        btnY2.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//this checks if the game ended in a draw
                        round = true;//sets it to the users round after the computer has won
                    }
                    else if ((btnX3.Text == "X") && (btnY2.Text == "X") && (btnZ1.Text != "X") && (btnZ1.Text != "O"))
                    {
                        btnZ1.Text = "O";//setting the button to the text "O"
                        btnZ1.Enabled = false;//disabling the button 
                        winCheckO();//checks if the computer made the winning move
                        drawCheck();//t//sets it to the users round after the computer has wonhis checks if the game ended in a draw
                        round = true;
                    }
                    else
                    {
                        if ((!winCheckO()) && (!winCheckX()) && (!drawCheck()))
                        {
                            btnList[rndIndex].Text = "O";//setting the random button to O
                            btnList[rndIndex].Enabled = false;//disabling the button so that it cant be pressed again
                            btnList.RemoveAt(rndIndex);//removing the button from the list
                            winCheckO();//checks if the computer made the winning move
                                        //this checks if the game ended in a draw
                            drawCheck();//this checks if the game ended in a draw
                            round = true;//sets it to the users round after the computer made a move
                        }
                    }
                }
            }
        }

        private bool winCheckO()//a boolean method I made to check if the computer won
        {
            lblXScore.Text = "X-Score: " + scoreX;//outputs the X score(user)
            lblOScore.Text = "O-Score: " + scoreO;//outputs the O score(computer)
            if (((btnX1.Text == "O") && (btnX2.Text == "O") && (btnX3.Text == "O")) || //Checking if rows are equal
                ((btnY1.Text == "O") && (btnY2.Text == "O") && (btnY3.Text == "O")) || //Checking if rows are equal
                ((btnZ1.Text == "O") && (btnZ2.Text == "O") && (btnZ3.Text == "O")) || //Checking if rows are equal
                ((btnX1.Text == "O") && (btnY1.Text == "O") && (btnZ1.Text == "O")) || //Checking if columns are equal
                ((btnX2.Text == "O") && (btnY2.Text == "O") && (btnZ2.Text == "O")) || //Checking if columns are equal
                ((btnX3.Text == "O") && (btnY3.Text == "O") && (btnZ3.Text == "O")) || //Checking if columns are equal
                ((btnX1.Text == "O") && (btnY2.Text == "O") && (btnZ3.Text == "O")) || //Checking if diagonals are equal
                ((btnZ1.Text == "O") && (btnY2.Text == "O") && (btnX3.Text == "O")) //Checking if diagonals are equal
                )
            {
                //message to show that the user lost 
                MessageBox.Show("May God fill your heart with strength to bear the shame!\nBeacause you just lost the game SUCKA!!\nK.O.ed!");
                scoreO++;//accumulates computer's score
                btnX1.Text = "";//leaves the button empty
                btnX1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnX2.Text = "";//leaves the button empty
                btnX2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnX3.Text = "";//leaves the button empty
                btnX3.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY1.Text = "";//leaves the button empty
                btnY1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY2.Text = "";//leaves the button empty
                btnY2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY3.Text = "";//leaves the button empty
                btnY3.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ1.Text = "";//leaves the button empty
                btnZ1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ2.Text = "";//leaves the button empty
                btnZ2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ3.Text = "";//leaves the button empty
                btnZ3.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnList = new List<Button> { btnX1, btnX2, btnX3, btnY1, btnY2, btnY3, btnZ1, btnZ2, btnZ3 };//refreshing the list elements after making removing most of them during the playing process
                //round = true;
                matchCheck();//checking if either opponent won in a game best of 3
                return true;//since this is a boolean method, it must return a value of true or false, so if O wins, the method will hold a value of true
            }
            return false;//if the if statement isnt true, then the method will hold a false value
        }

        private bool winCheckX()//a boolean method I made to check if the user won
        {
            lblXScore.Text = "X-Score: " + scoreX;//outputs the X score(user)
            lblOScore.Text = "O-Score: " + scoreO;//outputs the O score(computer)
            if (((btnX1.Text == "X") && (btnX2.Text == "X") && (btnX3.Text == "X")) || //Checking if rows are equal
                ((btnY1.Text == "X") && (btnY2.Text == "X") && (btnY3.Text == "X")) || //Checking if rows are equal
                ((btnZ1.Text == "X") && (btnZ2.Text == "X") && (btnZ3.Text == "X")) || //Checking if rows are equal
                ((btnX1.Text == "X") && (btnY1.Text == "X") && (btnZ1.Text == "X")) || //Checking if columns are equal
                ((btnX2.Text == "X") && (btnY2.Text == "X") && (btnZ2.Text == "X")) || //Checking if columns are equal
                ((btnX3.Text == "X") && (btnY3.Text == "X") && (btnZ3.Text == "X")) || //Checking if columns are equal
                ((btnX1.Text == "X") && (btnY2.Text == "X") && (btnZ3.Text == "X")) || //Checking if diagonals are equal
                ((btnZ1.Text == "X") && (btnY2.Text == "X") && (btnX3.Text == "X")))//Checking if diagonals are equal
            {
                //message to show that the user won
                MessageBox.Show("CONGRATULATIONS!! You Win");
                scoreX++;//accumulates user's score
                btnX1.Text = "";//leaves the button empty
                btnX1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnX2.Text = "";//leaves the button empty
                btnX2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnX3.Text = "";//leaves the button empty
                btnX3.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY1.Text = "";//leaves the button empty
                btnY1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY2.Text = "";//leaves the button empty
                btnY2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY3.Text = "";//leaves the button empty
                btnY3.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ1.Text = "";//leaves the button empty
                btnZ1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ2.Text = "";//leaves the button empty
                btnZ2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ3.Text = "";//leaves the button empty
                btnZ3.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnList = new List<Button> { btnX1, btnX2, btnX3, btnY1, btnY2, btnY3, btnZ1, btnZ2, btnZ3 };//refreshing the list elements after making removing most of them during the playing process
                matchCheck();//checking if either opponent won in a game best of 3
                return true;//since this is a boolean method, it must return a value of true or false, so if O wins, the method will hold a value of true
            }
            return false;//if the if statement isnt true, then the method will hold a false value
        }

        private bool matchCheck()//a boolean method I made to check if the user or the computer won in a match best of 3
        {
            //if the user won more than once, than the user cant rebuddle a victory since the game is best of 3 and if the user won twice, he won the match itself
            if (scoreX > 1)
            {
                this.Hide();//hides the Tic tac toe game I learnt this here(https://www.techotopia.com/index.php/Hiding_and_Showing_Forms_in_C_Sharp#Hiding_Forms_in_C.23)
                swftSalv swiftSalvation = new swftSalv(swftSalv.level, swftSalv.Round);//calling the TicTacToe form 2nd Component that has the parameters and arguments that dont include the strart up screen and placing it in a frmXO. I learnt this for my mom ;).  I really need help, I could fond anything on the web, so she rescued me. Hevent you ever asked your mom for help Grandma??
                swiftSalvation.ShowDialog();//goes back to the initial SwiftSalvation game
                return true;//since this is a boolean method, it must return a value of true or false, so if O wins, the method will hold a value of true
            }
            //if the computer won more than once, than the user cant rebuddle a victory since the game is best of 3 and if the computer won twice, he won the match itself
            else if (scoreO > 1)
            {
                this.Hide();//hides the Tic tac toe game I learnt this here(https://www.techotopia.com/index.php/Hiding_and_Showing_Forms_in_C_Sharp#Hiding_Forms_in_C.23)
                for (int computerWin = 0; computerWin < 4; computerWin++)//for loop created to inform the user that they lost. Setting computerWin to 0. The code will run as long as computerWin is less than 4. Accumulation of computerWin
                {
                    if (computerWin == 0)//this happens first because computerWin is set as 0 in the for loop
                    {
                        MessageBox.Show("Game Over!! The sun exploded and life as you know it died, including yourself");//displaying and informing the user that they lost
                    }
                    else if (computerWin == 1)//this happens second after computerWin's accumulation in the for loop
                    {
                        MessageBox.Show("HaHa");//displaying and informing the user that the computer is laughing at it in its face
                    }
                    else if (computerWin == 2)//this happens third after computerWin's accumulation in the for loop
                    {
                        MessageBox.Show("You Suck, Computers are superior");//displaying and informing the user that they suck and computers are superior
                    }
                    else if (computerWin == 3)//this happens fourth after computerWin's accumulation in the for loop
                    {
                        MessageBox.Show("A Baby could've won with their eyes closed");//displaying and informing the user that a baby is more capable than themselves
                    }
                }
                return true;//since this is a boolean method, it must return a value of true or false, so if O wins, the method will hold a value of true
            }
            return false;//if the if statement above does not meet, then the boolean will be set to a value of false
        }
        //checking if Draw
        private bool drawCheck()//a boolean method I made to check if the user or the computer ended the game in a draw
        {
            //checks if all buttons are full of inputs and nobody won
            if ((btnX1.Text == "X" || btnX1.Text == "O") && (btnX2.Text == "X" || btnX2.Text == "O") &&
                (btnX3.Text == "X" || btnX3.Text == "O") && (btnY1.Text == "X" || btnY1.Text == "O") &&
                (btnY2.Text == "X" || btnY2.Text == "O") && (btnY3.Text == "X" || btnY3.Text == "O") &&
                (btnZ1.Text == "X" || btnZ1.Text == "O") && (btnZ2.Text == "X" || btnZ2.Text == "O") &&
                (btnZ3.Text == "X" || btnZ3.Text == "O") && (!winCheckX()) && (!winCheckO()))
            {
                MessageBox.Show("Draw");//displaying and informing the user that the game ended in a draw
                btnX1.Text = "";//leaves the button empty
                btnX1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnX2.Text = "";//leaves the button empty
                btnX2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnX3.Text = "";//leaves the button empty
                btnX3.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY1.Text = "";//leaves the button empty
                btnY1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY2.Text = "";//leaves the button empty
                btnY2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnY3.Text = "";//leaves the button empty
                btnY3.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ1.Text = "";//leaves the button empty
                btnZ1.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ2.Text = "";//leaves the button empty
                btnZ2.Enabled = true;//Enables the button so that the user gets to click the buttons
                btnZ3.Text = "";//leaves the button empty
                btnZ3.Enabled = true;//Enables the button so that the user gets to click the buttons
                round = true;//making it the user turn after the draw has been declared
                btnList = new List<Button> { btnX1, btnX2, btnX3, btnY1, btnY2, btnY3, btnZ1, btnZ2, btnZ3 };//refreshing the list elements after making removing most of them during the playing process
                return true;//since this is a boolean method, it must return a value of true or false, so if O wins, the method will hold a value of true
            }
            return false;//if the if statement above does not meet, then the boolean will be set to a value of false
        }
    }
}
